# -*- coding: utf-8 -*-
"""menghitung produksi panen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yokm8KJ7G712gF06wBkQYpJ1gyfINsRx
"""

def hitung_produksi_panen(BP, KAP):
  GK = ((100 - KAP) / (100 - 14) * BP)
  Beras = 0.62 * GK * 1000 #konversi ke gram
  Karung = Beras / 25 #1 karung 25 kg
  return Karung

BP = int(input("Bobot gabah panen (Ton) = "))
KAP = int(input("Kadar air panen (%) = "))

Karung_Beras = hitung_produksi_panen(BP, KAP)
print(2("Pak Tono panen {:.2f} Ton gabah kering, akan menghasilkan {:2f} Kg\nberas sebanyak {:.0f} karung beras").format(BP, Karung_Beras*25,Karung_Beras))