# -*- coding: utf-8 -*-
"""Visualisasi Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OGROq8wUi-sMxjFMf1lBRVTDnEiJzBnH
"""

data = [128,100,180,150,200,90,340,105,85,270,
        200,65,230,150,150,120,130,80,230,200,
        110,126,170,132,140,112,90,340,170,190]

min(data)
max(data)

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

plt.hist(data,bins=7)

import seaborn as sns
sns.set(color_codes=False)
sns.distplot(data, bins=7,axlabel="Harga keyboard", kde=False)

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
plt.hist(data,bins=7,cumulative=True)